name: Tests

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4.4.0
        with:
          node-version: node

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Check formatting (Prettier)
        run: npm run check
